// Helper: returns an ISO datetime string N days from now, used for "amazing offer" countdown timers
function futureDate(daysFromNow: number, hour = 23, minute = 59): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour, minute, 0, 0);
  // Format as "YYYY-MM-DDTHH:mm" (matches <input type="datetime-local"> and Date-parseable)
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export const initialCollections = [
  {
    slug: "royal-silk-collection",
    titlePersian: "کلکسیون ابریشم",
    subtitlePersian: "لطافتی که هر شب زیر انگشتات حسش می‌کنی",
    description:
      "ابریشم طبیعی با پنبه مصری ۸۰۰ شانه. ضد حساسیت. انقدر نرم که بعد از ده‌بار شستشو هم مثل روز اول می‌مونه.",
    imageUrl:
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=85",
    isFeatured: true,
  },
  {
    slug: "orthopedic-sleep",
    titlePersian: "بالش‌های ارگونومیک طبی",
    subtitlePersian: "صبح بدون گردن‌درد بیدار شو. واقعی، نه شعاری.",
    description:
      "مموری فوم هوشمند با ژل خنک‌کننده. بالشی که خودشو با تو تنظیم می‌کنه، نه تو باهاش.",
    imageUrl:
      "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1200&q=85",
    isFeatured: true,
  },
  {
    slug: "four-seasons-duvets",
    titlePersian: "لحاف‌های چهار فصل پر غاز طبیعی",
    subtitlePersian: "یه لحاف برای کل سال. زمستون گرمی، تابستون خنک.",
    description:
      "پر غاز طبیعی با دوخت سه‌بعدی. سبک، تنفس‌پذیر، بدون حساسیت. دیگه لازم نیست هر فصل لحاف عوض کنی.",
    imageUrl:
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=85",
    isFeatured: true,
  },
];

export const initialProducts = [
  {
    slug: "royal-silk-10-piece-venice",
    namePersian: "سرویس روتختی ۱۰ تکه ابریشم سلطنتی مدل ونیس",
    nameEnglish: "Royal Silk 10-Piece Bedding Set - Venice",
    category: "روتختی",
    categorySlug: "bedding-sets",
    price: 6800000,
    originalPrice: 8200000,
    shortDescription: "انقدر لطیف و نرمه که صبح‌ها دلت نمیاد از تخت بیای بیرون. ابریشم طبیعی با پنبه مصری ۸۰۰ شانه.",
    description:
      "سرویس ونیس رو ساختیم برای کسایی که بعد از یه روز طولانی و پراسترس، لایق یه آغوش نرم و لطیفن. ترکیب ۵۰٪ ابریشم طبیعی و ۵۰٪ پنبه مصری با بافت ۸۰۰ شانه یعنی چی؟ یعنی ملحفه‌ای که پوستت توش نفس می‌کشه، تعریق شبانه رو کم می‌کنه، و اونقدر نرمه که بعد از ده بار شستشو هم عین روز اول می‌مونه. توی این سرویس یه لحاف الیاف‌دار سه‌بعدی، ملحفه کش‌دار، ۴ تا روبالشی ابریشمی، ۲ تا روبالشی تزئینی و ۲ تا کوسن مبلمان هست. بسته‌بندی جعبه‌ای لوکسمون هم اگه برای هدیه یا جهیزیه می‌خوای، حسابی تحویل می‌گیری.",
    features: [
      "بافت ۸۰۰ شانه — یعنی لطافتی که زیر انگشتات حسش می‌کنی",
      "ترکیب ابریشم طبیعی + پنبه مصری درجه یک",
      "پارچه‌ای که نفس می‌کشه — تعریق شبانه رو فراموش کن",
      "بعد از ده‌ها بار شستشو هم رنگ و بافتش عوض نمیشه",
      "بسته‌بندی جعبه‌ای شکیل — هدیه بده، بدرخشی",
    ],
    specifications: {
      "جنس پارچه رویه": "ژاکارد ابریشمی ترک تحت لیسانس ایتالیا",
      "جنس پارچه زیرین": "۱۰۰٪ پنبه مصری تنفس‌پذیر",
      "تعداد تکه": "۱۰ تکه کامل (شامل لحاف، کاور، ۴ روبالشی، ۲ کوسن، ملحفه تشک)",
      "ابعاد تشک سازگار": "۱۶۰ در ۲۰۰ (کویین) و ۱۸۰ در ۲۰۰ (کینگ)",
      "نحوه شستشو": "شستشو با آب ۳۰ درجه در ماشین لباسشویی یا خشک‌شویی",
    },
    images: [
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["کویین (۱۶۰×۲۰۰)", "کینگ (۱۸۰×۲۰۰)", "سوپر کینگ (۲۰۰×۲۰۰)"],
    availableColors: [
      { name: "کرم طلایی سلطنتی", hex: "#D4C5A9" },
      { name: "زمردی دربار", hex: "#2C4C3E" },
      { name: "سفید صدفی", hex: "#F7F7F7" },
      { name: "آبی درباری", hex: "#2F455C" },
    ],
    rating: 4.9,
    reviewCount: 42,
    inStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isAmazingOffer: true,
    amazingOfferEnd: futureDate(3),
  },
  {
    slug: "egyptian-cotton-collage-set",
    namePersian: "سرویس روتختی دونفره پنبه مصری مدل کلاژ مینیمال",
    nameEnglish: "Egyptian Cotton 800TC Minimal Collage Set",
    category: "روتختی",
    categorySlug: "bedding-sets",
    price: 4900000,
    originalPrice: null,
    shortDescription: "پنبه ۱۰۰٪ خالص که با هر بار شستشو نرم‌تر و لطیف‌تر میشه. سادگی مدرن، کیفیت بی‌حاشیه.",
    description:
      "اگه اهل سادگی و کیفیت بی‌حاشیه‌ای، مدل کلاژ برای تو ساخته شده. پنبه مصری رو یه بار امتحان کنی، دیگه هیچ پارچه‌ای به دلت نمی‌شینه. الیاف بلندترش یعنی نرم‌تر از پنبه‌های معمولی — و جالب‌تر اینکه هرچی بیشتر بشوریش، لطیف‌تر میشه. ۶ تکه داره: کاور لحاف، ملحفه کش‌دار و ۴ تا روبالشی. طراحی مینیمالش با هر دیزاینی ست میشه. رنگ طوسی‌اش هم یه حس مدرن و آروم به اتاقت میده.",
    features: [
      "۱۰۰٪ پنبه مصری خالص — فرقشو با پنبه معمولی حس می‌کنی",
      "پوستت توش نفس می‌کشه، حتی اگه حساس باشه",
      "طراحی مینیمال که با هر دکوراسیونی جوره",
      "بدون پرز دادن، بدون جمع‌شدگی بعد از شستشو",
    ],
    specifications: {
      "جنس پارچه": "پنبه مصری ۶۰۰ شانه ارگانیک",
      "تعداد تکه": "۶ تکه (کاور لحاف، ملحفه کش‌دار، ۴ عدد روبالشی)",
      "کشور سازنده پارچه": "ترکیه (دوخت سفارشی نفیس)",
      "ضمانت کیفیت": "۲۴ ماه ضمانت ثبات رنگ و بافت",
    },
    images: [
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["کویین (۱۶۰×۲۰۰)", "کینگ (۱۸۰×۲۰۰)"],
    availableColors: [
      { name: "طوسی مینیمال", hex: "#8E939D" },
      { name: "کرم نود", hex: "#E5DACE" },
      { name: "سفید ابری", hex: "#FFFFFF" },
    ],
    rating: 4.8,
    reviewCount: 29,
    inStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
  },
  {
    slug: "velvet-jacquard-palma-set",
    namePersian: "سرویس روتختی ۶ تکه مخمل ژاکارد مدل پالما",
    nameEnglish: "Velvet Jacquard 6-Piece Palma Bedding Set",
    category: "روتختی",
    categorySlug: "bedding-sets",
    price: 5400000,
    originalPrice: 6100000,
    shortDescription: "ترکیب باشکوه مخمل ابریشمی و ساتن با طرح‌های برجسته کلاسیک برای اتاق خواب‌های مجلل.",
    description:
      "مدل پالما با الهام از معماری کلاسیک اروپایی طراحی شده و سطح رویی آن از مخمل ابریشمی نرم با نقش‌برجسته‌های ظریف تشکیل شده است. سطح داخلی که در تماس با بدن است از ساتن پنبه ۱۰۰٪ بافته شده تا لطافت فوق‌العاده‌ای هنگام خواب ایجاد کند. جلوه بصری این مدل در نورپردازی اتاق خواب بی‌نهایت چشم‌نواز است.",
    features: [
      "رویه مخمل ژاکارد ابریشمی با درخشش ملایم",
      "آستر داخلی ساتن پنبه ۱۰۰٪ ضد تعریق",
      "مقاومت بالا در برابر چروک شدن",
      "دوخت ظریف صنعتی با لبه‌دوزی دوبل",
    ],
    specifications: {
      "جنس پارچه": "مخمل ژاکارد + ساتن پنبه",
      "تعداد تکه": "۶ تکه (لحاف دوخته شده، ملحفه تشک، ۴ روبالشی)",
      "ابعاد": "۲۶۰ در ۲۴۰ سانتی‌متر (مناسب تخت‌های دونفره)",
    },
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["کینگ (۱۸۰×۲۰۰)", "سوپر کینگ (۲۰۰×۲۰۰)"],
    availableColors: [
      { name: "زرشکی شاهانه", hex: "#681D26" },
      { name: "سرمه‌ای عمیق", hex: "#1C2D42" },
      { name: "بژ شکلاتی", hex: "#9E826C" },
    ],
    rating: 4.7,
    reviewCount: 18,
    inStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    slug: "cooling-memory-foam-pillow",
    namePersian: "بالش طبی مموری فوم خنک‌کننده ارگونومیک",
    nameEnglish: "Ergonomic Cooling Memory Foam Orthopedic Pillow",
    category: "بالش",
    categorySlug: "pillows",
    price: 1450000,
    originalPrice: 1750000,
    shortDescription: "بالشی که خودشو با تو تنظیم می‌کنه. ژل خنک‌کننده + مموری فوم. صبح بدون گردن‌درد.",
    description:
      "می‌دونی چرا صبح‌ها با گردن‌درد بیدار میشی؟ چون بالشت سرتو توی یه زاویه غیرطبیعی نگه می‌داره. این بالش مموری فوم رو ساختیم تا این مشکل رو یه بار برای همیشه حل کنیم. با حرارت و وزن سر و گردنت نرم میشه و خودشو دقیقاً با فرم بدنت تنظیم می‌کنه — نه اینکه تو مجبور باشی بهش عادت کنی. یه لایه ژل خنک‌کننده روش هست که سرت رو تا ۳ درجه خنک‌تر نگه می‌داره. اگه توی تابستون عرق می‌ریزی و کلافه میشی، این ژل برات نعمته. رویه‌ش هم از بامبو ارگانیکه، قابل شستشو و ضد حساسیت.",
    features: [
      "مموری فوم آلمانی — با گرمای بدنت فرم می‌گیره و گودی گردن رو پر می‌کنه",
      "پد ژل خنک‌کننده — سرت ۳ درجه خنک‌تر، بدون عرق شبانه",
      "رویه بامبو ارگانیک — زیپ‌دار و قابل شستشو توی ماشین",
      "پیشنهاد فیزیوتراپیست‌ها برای کاهش دردهای گردن و شانه",
      "اگه خر و پف می‌کنی، زاویه درست سر و گردن می‌تونه کمکت کنه",
    ],
    specifications: {
      "ابعاد بالش": "۶۰ در ۴۰ سانتی‌متر با ارتفاع دوگانه ۱۲ و ۱۴ سانتی‌متر",
      "جنس هسته داخلی": "مموری فوم هوشمند آلمانی با پد ژل خنک‌کننده",
      "جنس رویه": "پارچه گردباف بامبو ضد آلرژی",
    },
    images: [
      "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["استاندارد طبی (۶۰×۴۰×۱۴)"],
    availableColors: [
      { name: "سفید بامبو", hex: "#F8F9FA" },
      { name: "آبی آسمانی ملایم", hex: "#D8E6F3" },
    ],
    rating: 5.0,
    reviewCount: 64,
    inStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isAmazingOffer: true,
    amazingOfferEnd: futureDate(2),
  },
  {
    slug: "luxury-goose-down-pillow",
    namePersian: "بالش پر غاز طبیعی لوکس مدل پرستیژ",
    nameEnglish: "Prestige Natural Hungarian Goose Down Pillow",
    category: "بالش",
    categorySlug: "pillows",
    price: 2800000,
    originalPrice: 3300000,
    shortDescription: "پر شده با ۹۰٪ پر کرک غاز مجارستانی؛ حس بی‌نظیر سبکی، نرمی و شناور بودن روی ابرها.",
    description:
      "بالش پرستیژ از باکیفیت‌ترین پر کرک (Down) غاز سفید مجارستانی تشکیل شده است که فرآیند شستشو و استریل ۳ مرحله‌ای ضد حساسیت را گذرانده است. پارچه رویه این بالش از جنس کتان ۱۰۰٪ با تراکم بافت بسیار بالا (Down-Proof) است که از خروج حتی ریزترین پرها جلوگیری می‌کند. این بالش برای افرادی که به دنبال خوابی به سبک هتل‌های ۷ ستاره هستند انتخابی بی‌رقیب است.",
    features: [
      "۹۰٪ پر کرک (Down) و ۱۰٪ پر ریز (Feather) خالص",
      "فرآیند استریل پیشرفته بدون کوچکترین بو یا حساسیت",
      "پارچه کتان ضد خروج پر (Down-Proof 400TC)",
      "برگشت‌پذیری فوق‌العاده و عمر مفید بیش از ۱۰ سال",
    ],
    specifications: {
      "وزن خالص پر": "۱۱۰۰ گرم خالص",
      "ابعاد": "۵۰ در ۷۰ سانتی‌متر (استاندارد بین‌المللی)",
      "کشور مبدا پر": "مجارستان (فرآوری در اروپا)",
    },
    images: [
      "https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["استاندارد (۵۰×۷۰)", "کینگ (۵۰×۹۰)"],
    availableColors: [
      { name: "سفید برفی هتل", hex: "#FFFFFF" },
    ],
    rating: 4.9,
    reviewCount: 37,
    inStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
  },
  {
    slug: "five-star-hotel-nano-pillow",
    namePersian: "بالش ضد حساسیت الیاف نانو هتل‌های ۵ ستاره",
    nameEnglish: "5-Star Hotel Hypoallergenic Nano-Fiber Pillow",
    category: "بالش",
    categorySlug: "pillows",
    price: 850000,
    originalPrice: null,
    shortDescription: "جایگزین فوق‌العاده پر طبیعی با الیاف میکروفایبر نانو؛ لطیف، قابل شستشو و اقتصادی.",
    description:
      "بالش الیاف نانو هتل‌های ۵ ستاره برای کسانی که به دنبال نرمی شبیه به پر اما با قابلیت شستشوی مکرر در ماشین لباسشویی هستند طراحی شده است. الیاف میکروفایبر نانو با ضخامتی کمتر از موی انسان بافته شده‌اند و خاصیت ارتجاعی خود را پس از سال‌ها استفاده حفظ می‌کنند.",
    features: [
      "الیاف میکروفایبر نانو ارگانیک (جایگزین پر)",
      "کاملاً قابل شستشو در ماشین لباسشویی بدون گلوله شدن",
      "رویه پنبه‌ای لطیف با حاشیه‌دوزی طلایی",
      "تایید شده توسط انجمن آلرژی برای مبتلایان به آسم",
    ],
    specifications: {
      "وزن": "۱۲۰۰ گرم",
      "ابعاد": "۵۰ در ۷۰ سانتی‌متر",
      "جنس الیاف": "میکروفایبر سیلیکونایز کره جنوبی",
    },
    images: [
      "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["استاندارد (۵۰×۷۰)"],
    availableColors: [
      { name: "سفید حاشیه طلایی", hex: "#FCFCFC" },
    ],
    rating: 4.7,
    reviewCount: 81,
    inStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
  },
  {
    slug: "swedish-goose-down-duvet",
    namePersian: "لحاف پر قو و غاز چهار فصل ارگانیک مدل سوئد",
    nameEnglish: "Organic 4-Season Goose Down Duvet - Sweden Model",
    category: "لحاف",
    categorySlug: "duvets",
    price: 7200000,
    originalPrice: 8900000,
    shortDescription: "سبک‌ترین لحاف ممکن. توی زمستون گرمی، توی تابستون خنک. دیگه لازم نیست هر فصل عوضش کنی.",
    description:
      "همه ما تجربش کردیم: یه لحاف داریم که زمستون خوبه ولی تابستون عرق می‌ریزیم. یه لحاف دیگه تابستون خنکه ولی زمستون از سرما می‌لرزیم. خب، چاره‌ش چیه؟ لحاف سوئد. پر شده با ۸۰٪ پر کرک غاز سیبری. دوخت خانه‌بندی سه‌بعدی (Baffle-Box) باعث میشه پرها یه جا جمع نشن و گرما یه‌دست توی همه جای لحاف پخش بشه. باورت نمیشه چقدر سبکه — ولی توی زمستون مثل یه عایق گرم عمل می‌کنه و توی تابستون چون پرِ غاز تنفس‌پذیره، خنک می‌مونه. کاور بیرونیش هم ۱۰۰٪ پنبه ارگانیکه که پر ازش بیرون نزنه.",
    features: [
      "پر کرک غاز سیبری ۸۰٪ — سبک ولی عایق حرارتی فوق‌العاده",
      "دوخت خانه‌بندی سه‌بعدی — پرها یه جا گلوله نمیشن",
      "چهار فصل — زمستون گرم، تابستون خنک",
      "بند نگهدارنده توی ۴ گوشه — محکم به کاور لحافت وصل میشه",
      "کاور پنبه ارگانیک ضد نفوذ پر — پر بیرون نمی‌زنه",
    ],
    specifications: {
      "ابعاد دونفره": "۲۲۰ در ۲۴۰ سانتی‌متر (مناسب تخت‌های کویین و کینگ)",
      "وزن پر خالص": "۱۶۰۰ گرم",
      "جنس رویه": "پنبه ارگانیک ۵۰۰ شانه Down-Proof",
    },
    images: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["تک‌نفره (۱۶۰×۲۲۰)", "دونفره (۲۲۰×۲۴۰)"],
    availableColors: [
      { name: "سفید طبیعی ارگانیک", hex: "#FAF8F5" },
    ],
    rating: 4.9,
    reviewCount: 31,
    inStock: true,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    slug: "bamboo-silk-hypoallergenic-duvet",
    namePersian: "لحاف ضد حساسیت الیاف بامبو و ابریشم ارگانیک",
    nameEnglish: "Organic Bamboo & Silk Hypoallergenic Duvet",
    category: "لحاف",
    categorySlug: "duvets",
    price: 3600000,
    originalPrice: null,
    shortDescription: "ترکیب گیاهی الیاف بامبو و ابریشم؛ ضد باکتری طبیعی، لطیف و بسیار سبک برای خوابی آرام.",
    description:
      "الیاف بامبو به صورت طبیعی حاوی ماده‌ای به نام «بامبو کان» هستند که مانع رشد باکتری و قارچ می‌شود. لحاف الیاف بامبو و ابریشم نفیس با جذب رطوبت ۶۰٪ بیشتر از پنبه، محیطی کاملاً خشک و بهداشتی برای خواب شما فراهم می‌کند و برای افرادی که شب‌ها احساس گرما یا تعریق می‌کنند بهترین انتخاب است.",
    features: [
      "خاصیت ضد باکتری و ضد بو به واسطه الیاف طبیعی بامبو",
      "جذب و تبخیر سریع رطوبت بدن در طول شب",
      "بسیار سبک و لطیف با پوشش ساتن پنبه ارگانیک",
      "قابل شستشو با آب سرد در ماشین لباسشویی",
    ],
    specifications: {
      "ترکیب الیاف داخلی": "۷۰٪ الیاف بامبو ارگانیک + ۳۰٪ میکروفایبر ابریشمی",
      "ابعاد": "۲۲۰ در ۲۴۰ سانتی‌متر (دونفره استاندارد)",
    },
    images: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["تک‌نفره (۱۶۰×۲۲۰)", "دونفره (۲۲۰×۲۴۰)"],
    availableColors: [
      { name: "سبز بامبو بسیار روشن", hex: "#EAF2EC" },
      { name: "سفید صدفی", hex: "#F8F8F8" },
    ],
    rating: 4.8,
    reviewCount: 23,
    inStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
  },
  {
    slug: "weighted-blanket-calming-12kg",
    namePersian: "پتو سنگین‌وزن درمانی (Weighted Blanket) ۱۲ کیلوگرمی آرامش",
    nameEnglish: "Calming Weighted Blanket 12kg - Deep Touch Pressure",
    category: "پتو",
    categorySlug: "blankets",
    price: 3100000,
    originalPrice: 3600000,
    shortDescription: "انگار یکی بغلت کرده. پتوی ۱۲ کیلویی که اضطراب رو می‌گیره و خواب عمیق میاره.",
    description:
      "اگه شب‌ها توی تخت غلت می‌زنی و خوابت نمی‌بره، اگه استرس کاری یا درسی امانت رو بریده، این پتو برات ساخته شده. پتوی سنگین‌وزن (Weighted Blanket) یه تکنیک ساده پزشکی به اسم «فشار عمیق» استفاده می‌کنه — همون حسی که یه آغوش محکم بهت میده. وزن ۱۲ کیلویی (که با میکروگوی‌های شیشه‌ای بی‌خطر توی سلول‌های ریز تقسیم شده) باعث ترشح سروتونین و ملاتونین میشه — همون هورمون‌های آرامش و خواب. یعنی بدنت آروم می‌گیره، کورتیزول (هورمون استرس) کم میشه، و تو بالاخره یه خواب عمیق و بی‌دغدغه رو تجربه می‌کنی. کاور مخمل مینکیش هم جداشدنی و قابل شستشوئه.",
    features: [
      "حس یه آغوش آروم — فشار عمیق درمانی برای کاهش اضطراب",
      "وزن ۱۲ کیلو — مناسب افراد ۸۰ تا ۱۱۰ کیلوگرم",
      "کاور مخمل مینکی نرم — جداشدنی و قابل شستشو",
      "۷ لایه محافظتی — گوی‌های وزنی بیرون نمی‌زنن",
      "پیشنهادشده برای بی‌خوابی، استرس و سندرم پای بی‌قرار",
    ],
    specifications: {
      "وزن پتو": "۱۲ کیلوگرم (توصیه شده برای افراد با وزن ۸۰ تا ۱۱۰ کیلوگرم)",
      "ابعاد": "۱۸۰ در ۲۰۰ سانتی‌متر",
      "جنس کاور بیرونی": "مخمل مینکی فوق‌العاده نرم با بافت حسی",
    },
    images: [
      "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["۸ کیلوگرمی (۱۵۰×۲۰۰)", "۱۲ کیلوگرمی (۱۸۰×۲۰۰)"],
    availableColors: [
      { name: "طوسی آرامش‌بخش", hex: "#7D848F" },
      { name: "سرمه‌ای شبستان", hex: "#223147" },
    ],
    rating: 5.0,
    reviewCount: 51,
    inStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
  },
  {
    slug: "florence-organic-silk-satin-sheet-set",
    namePersian: "ست ملحفه ۴ تکه ساتن ابریشم ارگانیک مدل فلورانس",
    nameEnglish: "Florence Organic Silk Satin Sheet 4-Piece Set",
    category: "روبالشی و ملحفه",
    categorySlug: "pillowcases",
    price: 2400000,
    originalPrice: 2900000,
    shortDescription: "نرم مثل ابریشم برای محافظت از سلامت مو و جلوگیری از چین و چروک پوست صورت در خواب.",
    description:
      "خوابیدن روی ملحفه و روبالشی‌های ساتن ابریشمی مدل فلورانس اصطکاک میان مو و سطح بالش را به حداقل می‌رساند که مانع موخوره، گره خوردن مو و ریزش آن می‌شود. همچنین سطح صاف و خنک آن از ایجاد خطوط چروک روی پوست صورت جلوگیری کرده و رطوبت طبیعی پوست را حفظ می‌کند. این ست شامل ملحفه دور کش‌دار تشک، ملحفه روانداز تخت و ۲ عدد روبالشی ابریشمی است.",
    features: [
      "محافظت از سلامت و درخشش موها و جلوگیری از موخوره",
      "جلوگیری از چروک شدن پوست صورت هنگام خوابیدن به پهلو",
      "کش‌دوزی ۳۶۰ درجه برای ثابت ماندن روی تشک‌های تا ارتفاع ۳۵ سانت",
      "بافت ساتن ابریشم ارگانیک با لطافت ابریشمی",
    ],
    specifications: {
      "جنس پارچه": "ساتن ابریشم ارگانیک ۴۰۰ شانه",
      "تعداد تکه": "۴ تکه (ملحفه تشک کش‌دار، ملحفه روکش، ۲ عدد روبالشی)",
      "ارتفاع کش تشک": "۳۵ سانتی‌متر (مناسب تشک‌های بلند طبی)",
    },
    images: [
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["کویین (۱۶۰×۲۰۰)", "کینگ (۱۸۰×۲۰۰)"],
    availableColors: [
      { name: "رزگلد لطیف", hex: "#E8C5C8" },
      { name: "شامپاینی درخشان", hex: "#EADCC9" },
      { name: "نقره‌ای مهتابی", hex: "#C5C9CD" },
      { name: "مشکی ابریشم", hex: "#1D1E22" },
    ],
    rating: 4.8,
    reviewCount: 45,
    inStock: true,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: false,
  },
  {
    slug: "waterproof-nano-mattress-protector",
    namePersian: "محافظ تشک ضد آب و تنفس‌پذیر نانو الیاف گردباف",
    nameEnglish: "Turkish Nano Waterproof & Breathable Mattress Protector",
    category: "محافظ تخت",
    categorySlug: "mattress-protectors",
    price: 1200000,
    originalPrice: null,
    shortDescription: "محافظت ۱۰۰٪ از تشک در برابر مایعات و تعریق با لایه تنفس‌پذیر نانو؛ بدون ایجاد صدا و گرما.",
    description:
      "محافظ تشک ضد آب نفیس با استفاده از لایه ممبران پلی‌اورتان (PU) نانو طراحی شده است که به هیچ عنوان اجازه عبور قطرات آب یا مایعات را به تشک نمی‌دهد، اما در عین حال به جریان هوا اجازه عبور می‌دهد تا تشک عرق نکند. برخلاف محافظ‌های قدیمی پلاستیکی، این محصول هیچ‌گونه صدای خش‌خش ایجاد نکرده و سطحی حوله‌ای و نرم دارد.",
    features: [
      "۱۰۰٪ ضد آب و ضد نفوذ هرگونه مایعات و لکه",
      "تنفس‌پذیر و جلوگیری از گرم شدن تشک هنگام خواب",
      "کاملاً بی‌صدا و بدون حس پلاستیکی تحت هیچ شرایطی",
      "دیواره کش‌دار ۳۶۰ درجه برای نصب و جداسازی آسان",
    ],
    specifications: {
      "جنس رویه": "پارچه حوله‌ای گردباف الیاف پنبه",
      "جنس لایه زیرین": "لایه نانو ممبران ضد آب تنفس‌پذیر ترک",
      "قابلیت شستشو": "شستشو با آب تا ۹۰ درجه جهت ضدعفونی کامل",
    },
    images: [
      "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["تک‌نفره (۹۰×۲۰۰)", "کویین (۱۶۰×۲۰۰)", "کینگ (۱۸۰×۲۰۰)"],
    availableColors: [
      { name: "سفید بهداشتی", hex: "#FFFFFF" },
    ],
    rating: 4.9,
    reviewCount: 78,
    inStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    isAmazingOffer: true,
    amazingOfferEnd: futureDate(5),
  },
  {
    slug: "nordic-chunky-knit-wool-bed-throw",
    namePersian: "شال تخت و مبل کشباف پشمی دست‌باف مدل نوردیک",
    nameEnglish: "Nordic Chunky Knit Wool Bed & Sofa Throw Blanket",
    category: "پتو",
    categorySlug: "blankets",
    price: 2100000,
    originalPrice: 2450000,
    shortDescription: "بافته شده با کاموای غول‌پیکر پشم مرینوس؛ جلوه‌ای گرم، صمیمی و بسیار جذاب برای دیزاین اتاق خواب.",
    description:
      "شال تخت کشباف مدل نوردیک یکی از پرطرفدارترین اکسسوری‌های دکوراسیون داخلی مدرن است. این شال از کاموای ضخیم پشم مرینوس استرالیایی و الیاف اکریلیک نرم به صورت دست‌باف تهیه شده است. انداختن این شال در گوشه تخت خواب یا روی کاناپه، بلافاصله حسی از صمیمیت، گرما و زیبایی مینیمال اسکاندیناویایی را به فضای شما می‌بخشد.",
    features: [
      "بافت ضخیم و بسیار نرم با پشم مرینوس و الیاف پریمیوم",
      "دست‌باف با کیفیت استودیویی و ماندگاری بالا",
      "بهترین گزینه برای عکاسی و دیزاین لوکس اتاق خواب",
      "بسیار گرم و دلپذیر برای شب‌های پاییزی و زمستانی",
    ],
    specifications: {
      "ابعاد": "۱۳۰ در ۱۷۰ سانتی‌متر",
      "وزن": "۲۴۰۰ گرم",
      "جنس الیاف": "پشم مرینوس ۶۰٪ + اکریلیک نرم ۴۰٪",
    },
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["استاندارد (۱۳۰×۱۷۰)"],
    availableColors: [
      { name: "کرم شیری اسکاندیناوی", hex: "#EFECE6" },
      { name: "خاکستری زغالی گرم", hex: "#4A4D52" },
      { name: "خردلی پاییزی", hex: "#C79E4C" },
    ],
    rating: 4.8,
    reviewCount: 34,
    inStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    slug: "hotel-bath-towel-set-6pc",
    namePersian: "ست حوله حمام هتلی ۶ تکه پنبه ترکیه",
    nameEnglish: "6-Piece Turkish Cotton Hotel Bath Towel Set",
    category: "حوله",
    categorySlug: "towels-main",
    price: 1650000,
    originalPrice: 1950000,
    shortDescription: "حوله‌هایی که بعد از حموم بغلت می‌کنن. پنبه ترکیه ۶۰۰ گرم. جذب بالا، کرکی و نرم.",
    description:
      "حسی که بعد از یه دوش گرم داری — و یه حوله نرم و کرکی دورت می‌پیچه. این حس رو با حوله‌های هتلی نفیس هر روز تجربه کن. ست ۶ تکه: ۲ تا تن‌پوش بزرگ، ۲ تا حوله دست، ۲ تا حوله صورت. پنبه ۱۰۰٪ ترکیه با گرماژ ۶۰۰ — یعنی ۳ برابر جذب آب بیشتر از حوله‌های معمولی. و جالب‌تر اینکه هرچی بیشتر بشوریش، کرکی‌تر و نرم‌تر میشه. دقیقاً مثل حوله‌های هتل‌های ۵ ستاره. حلقه آویز هم داره که راحت توی حموم نصبش کنی.",
    features: [
      "پنبه ۱۰۰٪ ترکیه — فرقشو با حوله‌های معمولی حس می‌کنی",
      "۳ برابر جذب آب بیشتر — سریع خشک میشی",
      "هرچی بیشتر بشوری، کرکی‌تر و نرم‌تر میشه",
      "پُرز نمیده، رنگ پس نمیده",
      "حلقه آویز — راحت توی حموم نصب کن",
    ],
    specifications: {
      "جنس": "۱۰۰٪ پنبه ترکیه گرماژ ۶۰۰",
      "تعداد تکه": "۶ تکه (۲ تن‌پوش، ۲ دست، ۲ صورت)",
      "نحوه شستشو": "شستشو با آب ۴۰ درجه، بدون سفیدکننده",
    },
    images: [
      "https://images.unsplash.com/photo-1620331311520-246422fd82f9?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["استاندارد (ست ۶ تکه)"],
    availableColors: [
      { name: "سفید هتلی", hex: "#FBFBFB" },
      { name: "طوسی نقره‌ای", hex: "#B8BEC4" },
      { name: "صورتی پودری", hex: "#E8C7C7" },
    ],
    rating: 4.8,
    reviewCount: 27,
    inStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: true,
    isAmazingOffer: true,
    amazingOfferEnd: futureDate(4),
  },
  {
    slug: "kitchen-linen-service-set",
    namePersian: "سرویس پارچه‌ای آشپزخانه ۵ تکه (پیشبند، دستکش، حوله)",
    nameEnglish: "5-Piece Kitchen Linen Service Set",
    category: "لوازم آشپزخانه",
    categorySlug: "kitchen-table",
    price: 890000,
    originalPrice: 1050000,
    shortDescription: "پیشبند، دستکش فر و حوله آشپزخانه هماهنگ؛ ترکیبی شیک و کاربردی برای آشپزخانه‌های مدرن.",
    description:
      "سرویس پارچه‌ای آشپزخانه نفیس شامل یک پیشبند سرآشپزی، یک جفت دستکش فر ضدحرارت، دو حوله دستی و یک زیرقابلمه‌ای است. تمامی اجزا با پارچه پنبه‌ای ضخیم و طرح‌های هماهنگ طراحی شده‌اند تا هم عملکرد بالا و هم زیبایی دکوراسیون آشپزخانه شما را تضمین کنند.",
    features: [
      "دستکش فر ضدحرارت تا ۲۵۰ درجه سانتی‌گراد",
      "پارچه پنبه‌ای ضخیم و قابل شستشو در ماشین لباسشویی",
      "طرح و رنگ‌بندی هماهنگ برای دکوراسیون آشپزخانه",
      "دوخت دوبل و مقاوم در برابر پارگی",
    ],
    specifications: {
      "جنس": "پنبه ۱۰۰٪ با آستر ضدحرارت",
      "تعداد تکه": "۵ تکه (پیشبند، ۲ دستکش، ۲ حوله)",
    },
    images: [
      "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["سایز استاندارد"],
    availableColors: [
      { name: "خردلی آشپزخانه", hex: "#C79E4C" },
      { name: "طوسی مدرن", hex: "#8E939D" },
    ],
    rating: 4.6,
    reviewCount: 19,
    inStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    slug: "anti-slip-entrance-doormat",
    namePersian: "پادری ورودی ضدلغزش طرح گلیم سنتی",
    nameEnglish: "Anti-Slip Traditional Kilim Entrance Doormat",
    category: "روفرشی",
    categorySlug: "rugs",
    price: 420000,
    originalPrice: 520000,
    shortDescription: "کف ضدلغزش لاستیکی و رویه پلی‌استر مقاوم؛ اولین برخورد زیبا با مهمانان شما در درگاه منزل.",
    description:
      "پادری ورودی نفیس با طرح گلیم سنتی ایرانی، ترکیبی از زیبایی و کارایی است. زیره این پادری از لاستیک ضدلغزش با دوام بالا ساخته شده که از سر خوردن جلوگیری می‌کند و رویه پلی‌استر مقاوم آن به‌راحتی گرد و خاک و رطوبت کفش را جذب و خشک می‌کند.",
    features: [
      "زیره لاستیکی ضدلغزش مقاوم در برابر رطوبت",
      "رویه پلی‌استر با طرح سنتی گلیم غیرقابل‌شست‌شویی رنگ",
      "قابل شستشو با آب و جارو برقی",
      "مناسب ورودی منزل، آشپزخانه و راهرو",
    ],
    specifications: {
      "ابعاد": "۴۰ در ۶۰ سانتی‌متر",
      "جنس رویه": "پلی‌استر بافت متراکم",
      "جنس زیره": "لاستیک طبیعی ضدلغزش",
    },
    images: [
      "https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["۴۰×۶۰ سانتی‌متر", "۵۰×۸۰ سانتی‌متر"],
    availableColors: [
      { name: "زرشکی سنتی", hex: "#6B4226" },
      { name: "سرمه‌ای گلیم", hex: "#3B3228" },
    ],
    rating: 4.7,
    reviewCount: 33,
    inStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
  },
  {
    slug: "bamboo-summer-floor-mat-roll",
    namePersian: "حصیر بامبو تابستانه رول مدل سنتی",
    nameEnglish: "Traditional Bamboo Summer Floor Mat Roll",
    category: "روفرشی",
    categorySlug: "rugs",
    price: 980000,
    originalPrice: null,
    shortDescription: "خنک، طبیعی و سنتی؛ بهترین انتخاب برای فرش کردن اتاق‌ها و ایوان در فصل گرما.",
    description:
      "حصیر بامبوی نفیس از چوب بامبوی طبیعی و درجه یک بافته شده و برای استفاده تابستانه در اتاق نشیمن، اتاق خواب یا ایوان مناسب است. سطح خنک و طبیعی آن حس دلپذیری از خنکی را در گرمای تابستان ایجاد می‌کند و به‌راحتی رول و جابه‌جا می‌شود.",
    features: [
      "چوب بامبوی طبیعی ضدحشره و بادوام",
      "ایجاد حس خنکی طبیعی در فصل تابستان",
      "قابل رول شدن برای جابه‌جایی و نظافت آسان",
      "حاشیه‌دوزی پارچه‌ای مقاوم دور تا دور حصیر",
    ],
    specifications: {
      "ابعاد": "۲۰۰ در ۳۰۰ سانتی‌متر",
      "جنس": "بامبوی طبیعی با حاشیه پارچه‌ای",
    },
    images: [
      "https://images.unsplash.com/photo-1615529151169-7b1ff50dc7c1?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["۱۵۰×۲۰۰", "۲۰۰×۳۰۰"],
    availableColors: [
      { name: "بامبو طبیعی", hex: "#7A8E72" },
    ],
    rating: 4.5,
    reviewCount: 12,
    inStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    slug: "washable-machine-area-rug",
    namePersian: "روفرشی ماشینی طرح ابریشم مدل سلطنتی",
    nameEnglish: "Machine-Washable Silk-Pattern Royal Area Rug",
    category: "روفرشی",
    categorySlug: "rugs",
    price: 3200000,
    originalPrice: 3900000,
    shortDescription: "بافت متراکم و طرح سلطنتی، قابل شستشو در ماشین لباسشویی؛ زیبایی فرش ابریشم با نگهداری بسیار ساده.",
    description:
      "روفرشی ماشینی نفیس با طرح‌های الهام‌گرفته از فرش‌های سلطنتی ایرانی بافته شده و کاملاً قابل شستشو در ماشین لباسشویی خانگی است. الیاف پلی‌پروپیلن به‌کاررفته در این محصول در برابر ریزش رنگ و سایش مقاوم است و برای اتاق نشیمن و پذیرایی گزینه‌ای ایده‌آل محسوب می‌شود.",
    features: [
      "قابل شستشو در ماشین لباسشویی خانگی",
      "طرح متراکم سلطنتی الهام‌گرفته از فرش‌های دستباف",
      "مقاوم در برابر ریزش رنگ و سایش روزانه",
      "زیره ضدلغزش برای ثبات کامل روی کف",
    ],
    specifications: {
      "ابعاد": "۲۰۰ در ۳۰۰ سانتی‌متر",
      "جنس": "الیاف پلی‌پروپیلن با تراکم بالا",
    },
    images: [
      "https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["۱۵۰×۲۰۰", "۲۰۰×۳۰۰", "۲۵۰×۳۵۰"],
    availableColors: [
      { name: "زرشکی سلطنتی", hex: "#6B4226" },
      { name: "سرمه‌ای کلاسیک", hex: "#3B3228" },
      { name: "بژ طلایی", hex: "#7A8E72" },
    ],
    rating: 4.9,
    reviewCount: 41,
    inStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isAmazingOffer: true,
    amazingOfferEnd: futureDate(6),
  },
  {
    slug: "velvet-jacquard-sofa-throw",
    namePersian: "شال مبل مخملی ژاکارد مدل ایمپریال",
    nameEnglish: "Imperial Velvet Jacquard Sofa Throw",
    category: "پتو",
    categorySlug: "blankets",
    price: 1580000,
    originalPrice: 1890000,
    shortDescription: "درخشش مخمل ژاکارد با نقوش برجسته کلاسیک؛ پوششی شیک برای محافظت و آراستن مبلمان شما.",
    description:
      "شال مبل ایمپریال از پارچه مخمل ژاکارد با نقوش برجسته کلاسیک بافته شده و علاوه بر زیبایی چشم‌نواز، از مبلمان شما در برابر سایش، ریزش مو و لکه محافظت می‌کند. حاشیه‌دوزی ریشه‌دار این محصول لمسی از سلطنت را به فضای پذیرایی شما اضافه می‌کند.",
    features: [
      "پارچه مخمل ژاکارد با نقوش برجسته کلاسیک",
      "محافظت مبلمان در برابر سایش، مو و لکه",
      "حاشیه‌دوزی ریشه‌دار با ظاهری لوکس",
      "قابل شستشوی خشک و اتو با دمای پایین",
    ],
    specifications: {
      "ابعاد": "۱۷۰ در ۲۴۰ سانتی‌متر",
      "جنس": "مخمل ژاکارد با ریشه ابریشمی",
    },
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["استاندارد (۱۷۰×۲۴۰)"],
    availableColors: [
      { name: "زرشکی امپراتوری", hex: "#6B4226" },
      { name: "طلایی گلی", hex: "#7A8E72" },
    ],
    rating: 4.7,
    reviewCount: 16,
    inStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    slug: "silk-pillowcase-duo-pack",
    namePersian: "روبالشی ابریشم خالص مدل بیوتی (بسته ۲ عددی)",
    nameEnglish: "Pure Silk Beauty Pillowcase Duo Pack",
    category: "روبالشی و ملحفه",
    categorySlug: "pillowcases",
    price: 980000,
    originalPrice: 1250000,
    shortDescription: "ابریشم خالص ۲۲ مومه برای محافظت از پوست و مو در خواب؛ خنک، لغزنده و ضد حساسیت.",
    description:
      "روبالشی ابریشم خالص مدل بیوتی از ابریشم درجه یک با تراکم ۲۲ مومه (Momme) بافته شده و به دلیل سطح صاف و لغزنده خود، اصطکاک بین مو و بالش را به حداقل می‌رساند. این محصول برای افرادی که به دنبال حفظ شادابی پوست صورت و جلوگیری از موخوره هستند، انتخابی ایده‌آل است.",
    features: [
      "ابریشم خالص ۱۰۰٪ با تراکم ۲۲ مومه",
      "کاهش اصطکاک مو و جلوگیری از موخوره",
      "خنک و تنفس‌پذیر در تمام فصول سال",
      "زیپ‌دار و مناسب برای بالش‌های استاندارد و طبی",
    ],
    specifications: {
      "جنس": "۱۰۰٪ ابریشم توت ۲۲ مومه",
      "تعداد": "۲ عدد در بسته",
      "ابعاد": "۵۰ در ۷۰ سانتی‌متر",
    },
    images: [
      "https://images.unsplash.com/photo-1616627561950-9f746e330187?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["استاندارد (۵۰×۷۰)"],
    availableColors: [
      { name: "شامپاینی درخشان", hex: "#EADCC9" },
      { name: "نقره‌ای مهتابی", hex: "#C5C9CD" },
      { name: "زرشکی مخملی", hex: "#6B4226" },
    ],
    rating: 4.9,
    reviewCount: 22,
    inStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: true,
  },
  {
    slug: "kids-hooded-poncho-towel",
    namePersian: "حوله کودک کلاه‌دار پونیو با طرح حیوانات",
    nameEnglish: "Kids Hooded Poncho Towel with Animal Design",
    category: "حوله",
    categorySlug: "towels-main",
    price: 590000,
    originalPrice: 690000,
    shortDescription: "حوله نرم و کلاه‌دار مخصوص کودکان با طرح‌های بامزه حیوانات؛ جذب سریع آب و لطافت روی پوست حساس کودک.",
    description:
      "حوله کودک پونیو نفیس با طراحی کلاه‌دار و طرح‌های شاد حیوانات، حمام کردن کودک را به تجربه‌ای لذت‌بخش تبدیل می‌کند. پارچه پنبه‌ای ۱۰۰٪ این حوله بسیار نرم و جاذب رطوبت است و برای پوست حساس نوزادان و کودکان کاملاً بی‌خطر و ضدحساسیت می‌باشد.",
    features: [
      "پارچه پنبه‌ای ۱۰۰٪ بسیار نرم و ضدحساسیت",
      "طراحی کلاه‌دار برای گرم نگه‌داشتن سر کودک",
      "جذب سریع رطوبت و خشک شدن آسان",
      "طرح‌های شاد و رنگارنگ حیوانات",
    ],
    specifications: {
      "جنس": "۱۰۰٪ پنبه ارگانیک",
      "سن مناسب": "۰ تا ۶ سال",
      "ابعاد": "۷۵ در ۷۵ سانتی‌متر",
    },
    images: [
      "https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["استاندارد (۷۵×۷۵)"],
    availableColors: [
      { name: "زرد خرگوشی", hex: "#E8C468" },
      { name: "صورتی خرسی", hex: "#DCB8AE" },
      { name: "آبی دلفینی", hex: "#8FB4C9" },
    ],
    rating: 4.8,
    reviewCount: 30,
    inStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    slug: "chef-apron-glove-combo",
    namePersian: "کمربند آشپزی و دستکش فر ست شده مدل شف",
    nameEnglish: "Chef Apron & Oven Glove Combo Set",
    category: "لوازم آشپزخانه",
    categorySlug: "kitchen-table",
    price: 650000,
    originalPrice: null,
    shortDescription: "پیشبند حرفه‌ای همراه با دستکش فر ضدحرارت؛ ترکیبی کاربردی برای عاشقان آشپزی خانگی.",
    description:
      "ست آشپزی مدل شف شامل یک پیشبند بلند با جیب جلو و یک جفت دستکش فر ضدحرارت تا ۲۵۰ درجه سانتی‌گراد است. این مجموعه از پارچه کتان ضخیم و بادوام تهیه شده و برای استفاده روزمره در آشپزخانه یا هدیه دادن به عاشقان آشپزی گزینه‌ای عالی است.",
    features: [
      "پیشبند بلند با جیب جلو و بند قابل تنظیم",
      "دستکش فر ضدحرارت تا ۲۵۰ درجه سانتی‌گراد",
      "پارچه کتان ضخیم و مقاوم در برابر لکه",
      "قابل شستشو در ماشین لباسشویی",
    ],
    specifications: {
      "جنس": "کتان ۱۰۰٪ با آستر ضدحرارت",
      "تعداد": "۲ تکه (پیشبند و دستکش)",
    },
    images: [
      "https://images.unsplash.com/photo-1495521821757-a1efb6729352?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["سایز استاندارد بزرگسال"],
    availableColors: [
      { name: "خاکستری آشپزخانه", hex: "#8E939D" },
      { name: "خردلی گرم", hex: "#C79E4C" },
    ],
    rating: 4.6,
    reviewCount: 14,
    inStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
  },
  {
    slug: "hypoallergenic-pillow-protector-set",
    namePersian: "محافظ بالش ضد حساسیت زیپ‌دار (بسته ۲ عددی)",
    nameEnglish: "Hypoallergenic Zippered Pillow Protector Set",
    category: "محافظ تخت",
    categorySlug: "mattress-protectors",
    price: 480000,
    originalPrice: 590000,
    shortDescription: "محافظت کامل بالش در برابر گرد و غبار، شپشک و آلرژن‌ها با پارچه میکروفایبر زیپ‌دار.",
    description:
      "محافظ بالش نفیس با استفاده از پارچه میکروفایبر با بافت بسیار متراکم تولید شده که مانع نفوذ گرد و غبار، شپشک و آلرژن‌ها به داخل بالش می‌شود. زیپ مخفی این محافظ به‌راحتی بسته و باز شده و کاملاً بی‌صدا است.",
    features: [
      "بافت متراکم ضد نفوذ گرد و غبار و شپشک",
      "زیپ مخفی و کاملاً بی‌صدا",
      "قابل شستشو در ماشین لباسشویی",
      "مناسب برای مبتلایان به آلرژی و آسم",
    ],
    specifications: {
      "جنس": "میکروفایبر متراکم ضدحساسیت",
      "تعداد": "۲ عدد در بسته",
      "ابعاد": "۵۰ در ۷۰ سانتی‌متر",
    },
    images: [
      "https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1000&q=85",
    ],
    availableSizes: ["استاندارد (۵۰×۷۰)"],
    availableColors: [
      { name: "سفید بهداشتی", hex: "#FFFFFF" },
    ],
    rating: 4.7,
    reviewCount: 18,
    inStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    slug: "reinforced-bedroom-storage-box",
    namePersian: "باکس رخت‌خواب شاسی‌دار ضد رطوبت مدل نظم",
    nameEnglish: "Reinforced Waterproof Bedroom Storage Box",
    category: "ارگانایزر و باکس",
    categorySlug: "organizers-bedding",
    price: 1250000,
    originalPrice: 1490000,
    shortDescription: "باکس بزرگ با شاسی فلزی داخلی برای نگهداری روتختی و پتو؛ تاشو، مقاوم و ضد رطوبت.",
    description: "باکس نظم مدل نظم با شاسی فلزی سبک و پارچه برزنتی ضد رطوبت طراحی شده است. درب زیپ‌دار، پنجره شفاف و دسته‌های تقویت‌شده جابه‌جایی و نگهداری روتختی، پتو و لباس‌های فصلی را آسان می‌کند.",
    features: ["شاسی فلزی داخلی ضد تغییر شکل", "پارچه برزنتی ضد رطوبت", "پنجره شفاف برای مشاهده محتویات", "قابل تا شدن و مناسب زیر تخت"],
    specifications: { "ابعاد": "۶۰×۴۰×۳۰ سانتی‌متر", "ظرفیت": "حدود ۸۰ لیتر", "جنس": "برزنت تقویت‌شده" },
    images: ["https://images.unsplash.com/photo-1558997519-83ea9252edf8?auto=format&fit=crop&w=1000&q=85"],
    availableSizes: ["۶۰×۴۰×۳۰", "۸۰×۴۵×۳۰"],
    availableColors: [{ name: "کرم نود", hex: "#7A8E72" }, { name: "طوسی فیلی", hex: "#8E939D" }],
    rating: 4.7, reviewCount: 21, inStock: true, isFeatured: true, isBestSeller: false, isNewArrival: true,
  },
  {
    slug: "waterproof-folding-travel-mat",
    namePersian: "زیرانداز سفری تاشو ضد آب مدل کمپ",
    nameEnglish: "Waterproof Folding Travel Picnic Mat",
    category: "سفر و پیک‌نیک",
    categorySlug: "travel",
    price: 890000,
    originalPrice: 1050000,
    shortDescription: "زیرانداز سبک و تاشو با رویه ضد آب و کیف حمل؛ مناسب سفر، پیک‌نیک و ساحل.",
    description: "زیرانداز سفری کمپ در چهار لایه سبک، مقاوم و ضدآب ساخته شده است. بعد از جمع شدن در کیف کم‌جا قرار می‌گیرد و برای خانواده‌هایی که در سفر به تمیزی و راحتی اهمیت می‌دهند انتخابی کاربردی است.",
    features: ["رویه ضد آب و قابل پاک شدن", "لایه عایق حرارتی در برابر زمین", "تاشو با کیف حمل", "سبک و مناسب صندوق خودرو"],
    specifications: { "ابعاد باز": "۲۰۰×۱۵۰ سانتی‌متر", "ابعاد بسته": "۳۵×۲۵ سانتی‌متر", "وزن": "۹۰۰ گرم" },
    images: ["https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=1000&q=85"],
    availableSizes: ["۱۵۰×۲۰۰"],
    availableColors: [{ name: "سبز مریم گلی", hex: "#8FA18C" }, { name: "سرمه‌ای", hex: "#3B3228" }],
    rating: 4.6, reviewCount: 11, inStock: true, isFeatured: false, isBestSeller: false, isNewArrival: true,
  },
  {
    slug: "kids-stars-bedding-set",
    namePersian: "سرویس روتختی کودک مدل ستاره‌های خواب",
    nameEnglish: "Kids Sleepy Stars Bedding Set",
    category: "کودک و نوجوان",
    categorySlug: "kids-travel",
    price: 1850000,
    originalPrice: 2190000,
    shortDescription: "اولین روتختی که کوچولوت باهاش خواب شیرین می‌بینه. پنبه نرم ضد حساسیت با طرح ستاره.",
    description: "پوست بچه‌ها از بزرگ‌ترها حساستره. برای همین این سرویس رو از پنبه ۱۰۰٪ ضد حساسیت دوختیم تا خیالت راحت باشه. طرح ستاره‌های بامزه و رنگ‌های ملایمش اتاق کودک رو یه عالمه دل‌نشین‌تر می‌کنه. ۵ تکه داره، مناسب تخت یک‌نفره. راستی، قابل شستشو توی ماشین لباسشوییه — می‌دونی که بچه‌ها چقدر زود لباس و ملحفه رو کثیف می‌کنن.",
    features: ["پنبه ۱۰۰٪ ضد حساسیت — مناسب پوست لطیف کودک", "رنگ‌های ایمن بدون مواد شیمیایی مضر", "قابل شستشو توی ماشین لباسشویی", "دوخت محکم — این کوچولو رو دست‌کم نگیر"],
    specifications: { "تعداد تکه": "۵ تکه", "مناسب": "تخت یک‌نفره کودک", "جنس": "پنبه ۱۰۰٪" },
    images: ["https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=1000&q=85"],
    availableSizes: ["یک‌نفره کودک (۱۲۰×۲۰۰)"],
    availableColors: [{ name: "آبی آسمانی", hex: "#A9C5D9" }, { name: "صورتی ملایم", hex: "#DCB8AE" }],
    rating: 4.8, reviewCount: 9, inStock: true, isFeatured: false, isBestSeller: false, isNewArrival: true,
  },
  {
    slug: "orthopedic-neck-support-pillow",
    namePersian: "بالش ارتوپدی گردن و زانو مدل سلامت",
    nameEnglish: "Orthopedic Neck and Knee Support Pillow",
    category: "سلامت و مراقبت",
    categorySlug: "health",
    price: 760000,
    originalPrice: 890000,
    shortDescription: "بالش طبی چندمنظوره برای پشتیبانی گردن، زانو و کمر؛ مناسب سالمندان و دوران نقاهت.",
    description: "بالش ارتوپدی سلامت با فوم با دانسیته مناسب، فشار را از روی زانو و مهره‌های گردن کم می‌کند. روکش زیپ‌دار و قابل شستشو و فرم چندمنظوره آن استفاده در خانه و سفر را آسان کرده است.",
    features: ["فوم حمایتی با حفظ فرم", "روکش ضد حساسیت و قابل شستشو", "مناسب گردن، زانو و کمر", "سبک و قابل حمل"],
    specifications: { "ابعاد": "۵۰×۳۰×۱۲ سانتی‌متر", "جنس هسته": "فوم حمایتی", "روکش": "میکروفایبر ضدحساسیت" },
    images: ["https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1000&q=85"],
    availableSizes: ["استاندارد طبی"],
    availableColors: [{ name: "سفید پزشکی", hex: "#FFFFFF" }],
    rating: 4.8, reviewCount: 15, inStock: true, isFeatured: false, isBestSeller: true, isNewArrival: false,
  },
];

export const initialReviews = [
  {
    productSlug: "royal-silk-10-piece-venice",
    authorName: "سارا رادمنش",
    authorCity: "تهران - فرمانیه",
    rating: 5,
    date: "۲ روز پیش",
    comment:
      "سرویس ونیس واقعاً بی‌نظیره! کیفیت پارچه ژاکارد و درخشش ابریشمش دقیقاً مثل عکس‌هاست و حتی از نزدیک زیباتره. بسته‌بندی جعبه‌ایش انقدر شیک بود که حس خرید از بهترین برندهای اروپایی رو به آدم می‌ده. بعد از اولین شستشو هم کوچکترین تغییری نکرد.",
    verifiedPurchase: true,
    helpfulCount: 14,
  },
  {
    productSlug: "royal-silk-10-piece-venice",
    authorName: "دکتر علیرضا میرزایی",
    authorCity: "اصفهان - مرداویج",
    rating: 5,
    date: "۱ هفته پیش",
    comment:
      "ما برای جهیزیه دخترم این ست رو سفارش دادیم. لطافت پنبه مصری زیرینش فوق‌العاده‌ست و اصلاً باعث تعریق شبانه نمیشه. ارسال فوری با پیک هم بسیار مرتب و به موقع انجام شد. ممنون از کالای خواب نفیس.",
    verifiedPurchase: true,
    helpfulCount: 9,
  },
  {
    productSlug: "cooling-memory-foam-pillow",
    authorName: "مهندس پیمان کاظمی",
    authorCity: "شیراز - ملاصدرا",
    rating: 5,
    date: "۳ روز پیش",
    comment:
      "من سال‌هاست درد شدید آرتروز گردن دارم و ده‌ها بالش مختلف رو امتحان کرده بودم. بالش مموری فوم نفیس به خاطر پد ژل خنک‌کننده‌اش و انحنای ارگونومیکی که داره، خواب شبم رو کلاً عوض کرد. صبح‌ها بدون درد و خشکی گردن بیدار میشم.",
    verifiedPurchase: true,
    helpfulCount: 22,
  },
  {
    productSlug: "cooling-memory-foam-pillow",
    authorName: "نیلوفر شاهرخی",
    authorCity: "مشهد - سجاد",
    rating: 5,
    date: "۲ هفته پیش",
    comment:
      "خنکی پد ژله‌ایش توی شب‌های گرم تابستون معجزه‌ست. اصلاً سر عرق نمی‌کنه و ارتفاع بالش کاملاً استاندارد و راحته. حتماً برای همسرم هم یکی دیگه سفارش می‌دم.",
    verifiedPurchase: true,
    helpfulCount: 11,
  },
  {
    productSlug: "egyptian-cotton-collage-set",
    authorName: "ترانه سلیمانی",
    authorCity: "تهران - سعادت‌آباد",
    rating: 5,
    date: "۵ روز پیش",
    comment:
      "پارچه‌ش واقعاً ۱۰۰ درصد پنبه خالصه. خیلی لطیف و خنکه، رنگ طوسی مینیمالش با دیزاین اتاق خواب مدرن ما خیلی هماهنگ شد. ممنون از مشاوره عالی تلفنی‌تون.",
    verifiedPurchase: true,
    helpfulCount: 7,
  },
  {
    productSlug: "weighted-blanket-calming-12kg",
    authorName: "آرش بهمن‌پور",
    authorCity: "کرج - عظیمیه",
    rating: 5,
    date: "۴ روز پیش",
    comment:
      "اگر مثل من بی‌خوابی عصبی یا استرس کاری دارید، این پتوی سنگین‌وزن رو بدون تردید بخرید. وزن ۱۲ کیلوییش طوری روی بدن میشینه که انگار توی یک آغوش امن هستید. خواب عمیقم حداقل ۲ برابر شده.",
    verifiedPurchase: true,
    helpfulCount: 19,
  },
  {
    productSlug: "florence-organic-silk-satin-sheet-set",
    authorName: "دکتر مریم سلطانی (متخصص پوست و مو)",
    authorCity: "تهران - زعفرانیه",
    rating: 5,
    date: "۱ هفته پیش",
    comment:
      "به عنوان پزشک همیشه به مراجعینم توصیه می‌کنم برای جلوگیری از شکنندگی مو و ایجاد خطوط خواب روی صورت، از روبالشی‌های ابریشم یا ساتن ابریشم استفاده کنند. ست فلورانس کیفیت دوخت و لطافت بسیار بالایی داره و شخصاً ازش استفاده می‌کنم.",
    verifiedPurchase: true,
    helpfulCount: 31,
  },
  {
    productSlug: "waterproof-nano-mattress-protector",
    authorName: "حمیدرضا شاکری",
    authorCity: "تبریز - ولیعصر",
    rating: 5,
    date: "۳ هفته پیش",
    comment:
      "اصلاً باورم نمیشد محافظ ضد آب باشه اما هیچ صدای پلاستیکی نده! سطح رویش کاملاً نخی و حوله‌ایه و اصلاً باعث گرم شدن تشک نمیشه. برای تشک‌های گران‌قیمت حتماً ضروریه.",
    verifiedPurchase: true,
    helpfulCount: 15,
  },
];
